language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t reactapp -f Dockerfile.dev .

scripts:
  - docker run -e CI=true reactapp npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us=west-2"
  app: "reactapp"
  env: "docker-env"
  bucket_name: ""
  bucket_path: "foldername inisde bucket"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
